input {
  file {
    # path => "/usr/share/logstash/logs/*.log"
    path => "D:/MyWorkbench/Projects/AppLogs/CodingLemon/*.log"
    start_position => "beginning"
    codec => "json"
  }
}

filter {
  if [fields][logtype] == "codinglemons-backend" {
    json {
      source => "message"
    }
    
    date {
      match => [ "@timestamp", "yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSSZZ" ]
    }
    
    mutate {
      add_field => { "service" => "codinglemons-backend" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "codinglemon-backend-logs-%{+YYYY.MM.dd}"
  }
  
  stdout {
    codec => rubydebug
  }
}