#MongoDB properties
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=cl_backend_dev
spring.data.mongodb.password=ENC(FxNhdTaFlfIJ3XnZp721QzCxV9OrxDIoNDxd0KJS43Fg9PmLBLRoILm2Z4EEg9tN)
spring.data.mongodb.database=coding_lemon_dev
spring.data.mongodb.replica-set-name=rs0

# Redis properties
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.password=ENC(ZjIvqDCmJ9P2JOvQypJbcL0/cTQPw5VT+Ohb00F1twa7GXu6T+TTjWNMlhBdUAvu)
